version: '3'

services:

    database:
        image: postgres
        volumes: 
            - database:/var/lib/postgresql/data
        ports:
            - 7777:5432
        environment:
          POSTGRES_PASSWORD: postgres

volumes:
  database: {}